In [2]:
import pandas as pd
corpus = pd.read_csv(r"C:\Users\Eamon\Downloads\text_master.csv")
corpus

labels                                           big_text
0           0  hopson  a bill to be entitled an act relating ...
1           0  hochberg  a bill to be entitled an act relatin...
2           0  crabb  a bill to be entitled an act relating t...
3           0  morrison  a bill to be entitled an act relatin...
4           1  mccall  a bill to be entitled an act relating ...
...       ...                                                ...
44034       1    morales of maverick hb a noa 4667 a bill to ...
44035       1    murr hb a noa 4668 a bill to be entitled an ...
44036       1    cain hb a noa 4669 a bill to be entitled an ...
44037       0    capriglione hb a noa 4670 a bill to be entit...
44038       0    a johnson of harris hb a noa 4671 a bill to ...

[44039 rows x 2 columns]

In [53]:
indices_remove = []
for x in range(len(corpus['big_text'])):
    if(not isinstance(corpus.iloc[x]['big_text'], str)):
        indices_remove.append(x)
        print(corpus.iloc[x]['big_text'])
        
indices_remove

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan


[7813,
 7816,
 7829,
 7847,
 7886,
 7896,
 9785,
 9847,
 10412,
 11919,
 11931,
 11932,
 11935,
 11939,
 11940,
 11945,
 11963,
 11983,
 12022,
 12029,
 12031,
 12056,
 12066,
 24975,
 29568,
 33901,
 39369,
 40617,
 41923,
 42089,
 43936,
 43974]

In [54]:
for x in indices_remove:
    corpus = corpus.drop(index=x)

In [55]:
indices_remove = []
for x in range(len(corpus['big_text'])):
    if(not isinstance(corpus.iloc[x]['big_text'], str)):
        indices_remove.append(x)
        print(corpus.iloc[x]['big_text'])
        
indices_remove

[]

In [56]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus['big_text'], 
                                                    corpus['labels'], test_size=0.2,
                                                    random_state=42)


In [57]:
import tensorflow as tf

In [58]:
type(X_train)

pandas.core.series.Series

In [64]:

X_train_tensor = tf.convert_to_tensor(X_train)
X_test = tf.convert_to_tensor(X_test)
y_train = tf.convert_to_tensor(y_train)
y_test = tf.convert_to_tensor(y_test)

In [78]:
X_train_tensor

<tf.Tensor: shape=(35205,), dtype=string, numpy=
array([b'davis of dallas  a bill to be entitled an act relating to disciplinary actions affecting certain pharmacy technicians be it enacted by the legislature of the state of texas  occupations code is amended to read as follows except as otherwise provided by this subsection the the board may take disciplinary action under  if the board determines that the applicant or after the date of the person \xe2\x80\x99s original application the registrant has violated this subtitle or a rule adopted under this subtitle engaged in gross immorality as that term is defined by the rules of the board engaged in any fraud deceit or misrepresentation as those terms are defined by the rules of the board in seeking a registration to act as a pharmacy technician been convicted of or placed on deferred adjudication community supervision or deferred disposition or the applicable federal equivalent for a misdemeanor involving moral turpitude or under chapte

In [79]:
vocab_size = 10000
text_vec_layer = tf.keras.layers.TextVectorization(max_tokens=vocab_size, 
                                                   output_mode="tf_idf")
text_vec_layer.adapt(np.array([corpus['big_text']]).flatten())

KeyboardInterrupt: 

In [74]:
text_vec_layer

In [75]:
text_vec_layer(["Pollution", "the"])

<tf.Tensor: shape=(2, 10000), dtype=float32, numpy=
array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.6931358, 0.       , ..., 0.       , 0.       ,
        0.       ]], dtype=float32)>

In [77]:
embed_size = 128
tf.random.set_seed(42)
model = tf.keras.Sequential([
    text_vec_layer,
    tf.keras.layers.Embedding(vocab_size, embed_size, mask_zero=True),
    tf.keras.layers.LSTM(128, dropout=0.2),
    tf.keras.layers.Dense(1, activation="sigmoid")
])
model.compile(loss="binary_crossentropy", optimizer="nadam",
              metrics=["accuracy"])

early_stopping_cb = tf.keras.callbacks.EarlyStopping(
    monitor="accuracy", patience=5, restore_best_weights=True)

history = model.fit(X_train_tensor, y_train, validation_data=(X_test, y_test), epochs=20, 
                    callbacks=[early_stopping_cb], verbose=1)

Epoch 1/20
  12/1101 [..............................] - ETA: 26:33:09 - loss: 0.6445 - accuracy: 0.7812

KeyboardInterrupt: 